version: '3.1'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elasticdata:/usr/share/elasticsearch/data
volumes:
  elasticdata:
    driver: local
networks:
  default:
    external:
      name: esbot